import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full lg:grid lg:grid-cols-2">
      <div className="flex flex-col justify-center gap-y-6 mx-auto w-[350px] min-h-screen py-12">
        {children}
      </div>
      <div className="hidden bg-muted lg:block bg-gradient-to-r from-rose-100 to-teal-100"></div>
    </div>
  );
}
